apiVersion: devops.lsym.org/v1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-sample
  namespace: devops
spec:
  stages:
    - name: build
      parallel: false
      tasks:
        - name: view-version
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/golang:1.24.3
          script: |
            #!/usr/bin/env bash
            echo "hello world,this is script shell"
          env:
            - name: GOOS
              value: linux

    - name: images
      parallel: true
      tasks:
        - name: build
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/openebs/alpine-bash:4.2.0
          script: |
            #!/usr/bin/env bash
            echo "hello"

        - name: shell-exec
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/openebs/alpine-bash:4.2.0
          script: |
            #!/usr/bin/env bash
            sleep 60
            ls -lh  

    - name: deploy
      parallel: false
      tasks:
        - name: deploy-to-staging
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/kubesphere/kubectl:v1.27.4
          script: |
            #!/usr/bin/env bash
            ls
